# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 16:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Location name')),
                ('manager_name', models.CharField(max_length=127, verbose_name='Location manager name')),
                ('manager_phone', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Telephone number must be entered in the format '0XXX XXX XXX'", regex='^0\\d{3}\\s\\d{3}\\s\\d{3}$')], verbose_name='Location manager phone')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=127)),
                ('romanian_name', models.CharField(blank=True, max_length=127)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Movie duration in minutes.')),
                ('format', models.CharField(blank=True, choices=[('dcp', 'DCP'), ('35', '35mm'), ('digital', 'Digital')], max_length=10)),
                ('over18', models.BooleanField(default=False, help_text='Is the movie rated R?')),
                ('spoken_language_1', models.CharField(blank=True, max_length=127, null=True)),
                ('spoken_language_2', models.CharField(blank=True, max_length=127, null=True)),
                ('original_subtitle', models.CharField(blank=True, max_length=127, null=True)),
                ('electronic_sub_1_language', models.CharField(blank=True, max_length=127, null=True)),
                ('electronic_sub_1_format', models.CharField(blank=True, max_length=127, null=True)),
                ('electronic_sub_2_language', models.CharField(blank=True, max_length=127, null=True)),
                ('electronic_sub_2_format', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('two_volunteers', models.BooleanField(default=False)),
                ('special_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Location')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Volunteer name')),
                ('email', models.CharField(max_length=127, verbose_name='Volunteer e-mail address')),
                ('age', models.PositiveIntegerField()),
                ('phone_1', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Telephone number must be entered in the format '0XXX XXX XXX'", regex='^0\\d{3}\\s\\d{3}\\s\\d{3}$')], verbose_name='Volunteer phone')),
                ('phone_2', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message="Telephone number must be entered in the format '0XXX XXX XXX'", regex='^0\\d{3}\\s\\d{3}\\s\\d{3}$')], verbose_name='Volunteer phone')),
                ('language_1', models.CharField(blank=True, max_length=127, null=True)),
                ('language_2', models.CharField(blank=True, max_length=127, null=True)),
                ('language_3', models.CharField(blank=True, max_length=127, null=True)),
                ('language_4', models.CharField(blank=True, max_length=127, null=True)),
            ],
        ),
    ]
