# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20170531_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='laptop_sn',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Laptop serial number'),
        ),
    ]
