# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_location_laptop_sn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='original_name',
            new_name='original_title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='romanian_name',
            new_name='romanian_title',
        ),
        migrations.AddField(
            model_name='movie',
            name='english_title',
            field=models.CharField(default='', max_length=127),
            preserve_default=False,
        ),
    ]
