# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20170531_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['internal_id']},
        ),
        migrations.AddField(
            model_name='location',
            name='internal_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
