# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 17:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_auto_20170602_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 900), help_text='Movie duration in minutes.', verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.DurationField(help_text='Movie duration in minutes.', verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='volunteerschedule',
            name='projection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='entities.Projection'),
        ),
        migrations.AlterField(
            model_name='volunteerschedule',
            name='volunteer_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_1', to='entities.Volunteer'),
        ),
        migrations.AlterField(
            model_name='volunteerschedule',
            name='volunteer_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_2', to='entities.Volunteer'),
        ),
    ]
