# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-28 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_auto_20170825_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='cid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier', verbose_name='Content ID'),
        ),
        migrations.AlterField(
            model_name='location',
            name='assistant_2_name',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Assistant 2 name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='cid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier', verbose_name='Content ID'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier', verbose_name='Content ID'),
        ),
        migrations.AlterField(
            model_name='projection',
            name='cid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier', verbose_name='Content ID'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='cid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier', verbose_name='Content ID'),
        ),
        migrations.AlterField(
            model_name='volunteerschedule',
            name='cid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier', verbose_name='Content ID'),
        ),
    ]
