# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-29 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_auto_20180528_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteer',
            options={'ordering': ['name']},
        ),
    ]
