# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:19
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_availability_laptop_volunteerschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='assistant_name',
            new_name='assistant_1_name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='assistant_phone',
            new_name='assistant_1_phone',
        ),
        migrations.AddField(
            model_name='location',
            name='assistant_2_name',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Assistant name'),
        ),
        migrations.AddField(
            model_name='location',
            name='assistant_2_phone',
            field=models.CharField(blank=True, help_text="Format: '0XXX XXX XXX'", max_length=50, null=True, validators=[django.core.validators.RegexValidator(message="Telephone number must be entered in the format '0XXX XXX XXX'", regex='^0\\d{3}\\s\\d{3}\\s\\d{3}$')], verbose_name='Assistant phone'),
        ),
    ]
