from .settings import *  # noqa: F403

DEBUG = True

ALLOWED_HOSTS.extend(['0.0.0.0', 'localhost'])  # noqa: F405

X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_BROWSER_XSS_FILTER = False
SECURE_SSL_REDIRECT = False
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
