name: CI

on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: "vms"
  REGISTRY: "registry.digitalocean.com/mitza-docker-registry"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Add environment variables to .env
      run: |
        echo "ENVIRONMENT=production" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_HOST_AUTH_METHOD=md5" >> .env

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 180

    - name: Remove all old images
      run: if [ ! -z "$(doctl registry repository list | grep "$IMAGE_NAME")" ]; then doctl registry repository delete-manifest $IMAGE_NAME $(doctl registry repository list-tags $IMAGE_NAME | grep -o "sha.*") --force; else echo "No repository"; fi

    - name: Push image
      run: |
        docker tag $IMAGE_NAME $REGISTRY/$IMAGE_NAME
        docker push $REGISTRY/$IMAGE_NAME

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    needs: build_and_push
    steps:
      - name: Deploy to DigitalOcean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.SSHKEY }}
          envs: IMAGE_NAME,REGISTRY,{{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          script: |
            docker login -u ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} -p ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} registry.digitalocean.com
            docker stop $IMAGE_NAME
            docker rm $IMAGE_NAME
            docker run -d --restart always --name $IMAGE_NAME $REGISTRY/$IMAGE_NAME:latest
