name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  IMAGE_NAME: vms
  REGISTRY: registry.digitalocean.com/mitza-docker-registry

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: Checkout master
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Push image
      run: |
        docker tag $IMAGE_NAME registry.digitalocean.com/$REGISTRY/$IMAGE_NAME
        docker push registry.digitalocean.com/$REGISTRY/$IMAGE_NAME
